#slogan: ""

menu:
  - title: 首页
    url: 
    intro: ""
    icon: "fa fa-home"
  - title: 存档
    url: archives
    intro: ""
    icon: "fa fa-list"
  - title: 个人简历
    url: gc-resume
    intro: ""
    icon: "fa fa-info-circle"

links:
  - title: "source"
    url: http://www.github.com/gui-che
    intro: "My Github account."
    icon: "fa fa-github"


widgets:
# - search
- category
# - tagcloud
- recent_posts  
- links

rss: 
fancybox: false
favicon: favicon.png
google_analytics: 
